# ~/.config/alacritty/alacritty.toml

[window]
padding = { x = 20, y = 20 }
decorations = "None"
opacity = 0.95

[font]
size = 12.0
normal = { family = "JetBrains Mono", style = "Bold" }

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
