[colors.bright]
black = "#333333"
blue = "#5555ff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 11.2

[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"

[font.italic]
family = "JetBrains Mono"
style = "Bold"

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0
title = "Ranger - Neobrutalist File Manager"

[window.padding]
x = 20
y = 20
